#!/bin/bash

# DealSourceAI Tools Setup Script
# Automates setup of required tools (CRM, email, calendar, etc.)

set -e

echo "🛠️  DealSourceAI Tools Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This script will help you set up the required tools:"
echo "1. Domain registration"
echo "2. Email setup"
echo "3. Calendar scheduling"
echo "4. CRM setup"
echo "5. Email enrichment"
echo ""
read -p "Continue? (y/n): " confirm

if [ "$confirm" != "y" ]; then
    echo "Cancelled."
    exit 0
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 SETUP CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 1. Domain
echo "[ ] 1. Domain Registration"
echo "    → Go to: https://www.namecheap.com"
echo "    → Search for: dealsourceai.com"
echo "    → Cost: ~$12/year"
echo ""
read -p "Press Enter when done (or 's' to skip): " response
echo "    ✓ Domain registered"
echo ""

# 2. Email
echo "[ ] 2. Professional Email Setup"
echo "    → Go to: https://workspace.google.com"
echo "    → Create: founders@dealsourceai.com"
echo "    → Cost: $6/user/month"
echo ""
read -p "Press Enter when done (or 's' to skip): " response
echo "    ✓ Email configured"
echo ""

# 3. Calendar
echo "[ ] 3. Calendar Scheduling"
echo "    → Go to: https://calendly.com"
echo "    → Create account with founders@dealsourceai.com"
echo "    → Set availability: 9am-5pm, 15-min demo slots"
echo "    → Cost: Free (or $10/mo for Pro)"
echo ""
read -p "Press Enter when done (or 's' to skip): " response
echo "    ✓ Calendly configured"
echo ""

# 4. CRM
echo "[ ] 4. CRM Setup"
echo "    → Go to: https://www.hubspot.com/products/crm"
echo "    → Sign up for Free CRM"
echo "    → Import contacts from: go-to-market/target-customers/"
echo "    → Cost: Free"
echo ""
read -p "Press Enter when done (or 's' to skip): " response
echo "    ✓ CRM configured"
echo ""

# 5. Email Enrichment
echo "[ ] 5. Email Enrichment"
echo "    → Choose one:"
echo "      • Hunter.io - https://hunter.io ($49/mo)"
echo "      • Apollo.io - https://apollo.io ($49/mo)"
echo "    → Upload CSV from target extraction"
echo ""
read -p "Press Enter when done (or 's' to skip): " response
echo "    ✓ Email enrichment configured"
echo ""

# 6. Optional Tools
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 OPTIONAL TOOLS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "[ ] 6. LinkedIn Sales Navigator (recommended)"
echo "    → Go to: https://business.linkedin.com/sales-solutions"
echo "    → Cost: $80/month"
echo "    → Use for: Advanced prospect search"
echo ""
echo "[ ] 7. Email Warmup (if sending cold emails)"
echo "    → Mailwarm.io or Lemwarm.com"
echo "    → Cost: $25/month"
echo "    → Start: 2 weeks before first outreach"
echo ""

# Save configuration
CONFIG_FILE="/mnt/e/projects/acquisition-system/.env.tools"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💾 SAVING CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

cat > "$CONFIG_FILE" << 'EOF'
# DealSourceAI Tools Configuration
# Generated by setup-tools.sh

# Domain
DOMAIN=dealsourceai.com

# Email
EMAIL=founders@dealsourceai.com

# Calendly
CALENDLY_URL=https://calendly.com/dealsourceai/demo

# CRM
CRM_PLATFORM=hubspot
CRM_URL=https://app.hubspot.com

# Email Enrichment
EMAIL_ENRICHMENT_PROVIDER=hunter.io

# Monthly Tool Costs
MONTHLY_COST=180

# Tools List
# - Google Workspace: $6/mo
# - Hunter.io: $49/mo
# - LinkedIn Sales Nav: $80/mo
# - Calendly: Free
# - HubSpot CRM: Free
# - Email Warmup: $25/mo
# - Mailwarm: $25/mo
# TOTAL: ~$180/mo
EOF

echo "✅ Configuration saved to: $CONFIG_FILE"
echo ""

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 SETUP SUMMARY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Domain: dealsourceai.com"
echo "✓ Email: founders@dealsourceai.com"
echo "✓ Calendar: calendly.com/dealsourceai/demo"
echo "✓ CRM: HubSpot (free tier)"
echo "✓ Email Enrichment: Hunter.io"
echo ""
echo "💰 Monthly Cost: ~$180"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Deploy landing page:"
echo "   ./scripts/deploy-landing-page.sh"
echo ""
echo "2. Extract targets:"
echo "   ./scripts/extract-targets.sh"
echo ""
echo "3. Start dashboard:"
echo "   ./scripts/start-dashboard.sh"
echo ""
echo "4. Send first outreach:"
echo "   Review: go-to-market/target-customers/OUTREACH_TEMPLATES.md"
echo ""
echo "✅ Setup complete!"
